# Generated by Django 5.2.4 on 2025-10-15 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_recipe_recipeingredient_recipereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Use this for custom ingredients not in products', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_ingredients', to='products.product'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(help_text='e.g. 2 cups, 1 kg', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recipereview',
            unique_together={('recipe', 'user')},
        ),
    ]
